### ISSUE TITLE
Can't use kite for sublime

### ISSUE THREAD

**Issue by bpru** [kiteco/plugins#113]
Hi, I installed kite for sublime following the steps shown in your website. However, although sublime has kite listed in the package list, it seems that kite is not working with my sublime...any idea?

**Comment by dhung09** [comment]
Hi @bpru 

1. Are there any errors in the Sublime console when you start Sublime?
2. What other packages do you have installed? You can check this by running the commands `Package Control: List Packages` and `Package Control: List Unmanaged Packages` in the command palette

**Comment by bpru** [comment]
Hi, the following is the error message in sublime console when I start sublime:
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/JCChiang/Library/Application Support/Sublime Text 3/Packages/KiteSublime/KiteSublime.py", line 15, in <module>
    from .lib.commands import *
  File "/Users/JCChiang/Library/Application Support/Sublime Text 3/Packages/KiteSublime/lib/commands.py", line 5, in <module>
    from ..lib.handlers import HoverHandler, SignaturesHandler
  File "/Users/JCChiang/Library/Application Support/Sublime Text 3/Packages/KiteSublime/lib/handlers.py", line 13, in <module>
    from ..vendor.jinja2 import Template
  File "/Users/JCChiang/Library/Application Support/Sublime Text 3/Packages/KiteSublime/vendor/jinja2/__init__.py", line 56, in <module>
    from jinja2.utils import Markup, escape, clear_caches, \
ImportError: cannot import name select_autoescape

**Comment by dhung09** [comment]
Thanks for reporting this issue. We have a fix for this that should be released later today. I'll update you when that happens!

**Comment by dhung09** [comment]
Hi @bpru - this has been fixed as of Kite  v0.20181108.1. Try uninstalling and reinstalling the Sublime plugin from the Copilot and let us know if it hasn't been fixed for you.

**Comment by bpru** [comment]
Hi, it worked. Thanks a lot!

**Comment by 183amir** [comment]
Hi I am hitting this issue and reinstalling kite plugin did not help:
```
reloading plugin KiteSublime.KiteSublime
Traceback (most recent call last):
  File "/home/Apps/sublime_text_3/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/.config/sublime-text-3/Packages/KiteSublime/KiteSublime.py", line 23, in <module>
    from .lib.commands import *
  File "/home/.config/sublime-text-3/Packages/KiteSublime/lib/commands.py", line 5, in <module>
    from ..lib.handlers import HoverHandler, SignaturesHandler
  File "/home/.config/sublime-text-3/Packages/KiteSublime/lib/handlers.py", line 18, in <module>
    from ..vendor.jinja2 import Template
  File "/home/.config/sublime-text-3/Packages/KiteSublime/vendor/jinja2/__init__.py", line 56, in <module>
    from jinja2.utils import Markup, escape, clear_caches, \
ImportError: cannot import name select_autoescape
```
I have the latest sublime text 3 : 3.2.2 build 3211
Kite version: 2.20200910.0

Could you please reopen this issue?
