### ISSUE TITLE
Cannot type certain characters in PyCharm's Python Console

### ISSUE THREAD

**Issue by jayBana** [kiteco/plugins#161]
* When I have Kite's PyCharm Plug-in enabled and I type `(`  in the "Python Console" from within PyCharm, I get the exception below.  Please note that the character is not actually displayed in the console.

* When I type `,`, I get the following weird behavior in the console:

![2020-01-02_21-41-43 (1)](https://user-images.githubusercontent.com/3785602/71695075-efd9b780-2da8-11ea-9296-20c0a2acb29d.gif)
> I first type `,` and then press the `<-` "back arrow" in the above gif screen recording.

```java
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'ext' of com/kite/intellij/lang/KitePythonSupport.supportsFileExtension must not be null
	at com.kite.intellij.lang.d.a(KitePythonSupport.java)
	at com.kite.intellij.lang.d.supportsFileExtension(KitePythonSupport.java)
	at com.kite.intellij.lang.e.a(LanguageSupportManager.java:24)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at com.kite.intellij.lang.e.B(LanguageSupportManager.java:24)
	at com.kite.intellij.lang.c.a(KiteLanguageSupport.java:35)
	at com.kite.intellij.lang.c.b(KiteLanguageSupport.java:29)
	at com.kite.intellij.lang.psi.refs.c.a(PsiReferenceTracker.java:58)
	at com.kite.intellij.lang.psi.refs.a.doCollectInformation(CollectHighlightingPass.java:43)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

---

**OS:** 

> macOS Catalina 10.15.2

**IDE:** 
> PyCharm 2019.3.1 (Professional Edition)
> Build #PY-193.5662.61, built on December 18, 2019
> For educational use only.
> Runtime version: 11.0.5+10-b520.17 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> macOS 10.15.2
> GC: ParNew, ConcurrentMarkSweep
> Memory: 2014M
> Cores: 4
> Registry: 
> Non-Bundled Plugins: com.dropbox.plugins.mypy_plugin, com.kite.intellij, com.leinardi.pycharm.pylint, net.vektah.codeglance, zielu.gittoolbox

**Kite**
> Version: 0.20191217.0
> PyCharm Plug-in Version: 1.3.1.193

**PyCharm's Python Console Settings**

![image](https://user-images.githubusercontent.com/3785602/71694556-72617780-2da7-11ea-93eb-c50f84b409da.png)

**Comment by notemissary** [comment]
Same problem occurs on Ubuntu LTS 18.04 and with the `(` character.

**Comment by metalogical** [comment]
Thanks for the bug report. We have a fix ready for release on Monday.

**Comment by jayBana** [comment]
@metalogical Let me know when the fix is released so I can re-enable the plugin in Pycharm after the update.

**Comment by shakhin85** [comment]
@metalogical, please let us know upon releasing the bug fix. Would appreciate a lot!

**Comment by metalogical** [comment]
The fix should be available if you update to the latest version of Kite (*.20200107.0). Thanks for your patience.

Feel free to re-open the issue if you encounter further issues.
