### ISSUE TITLE
Kite Plugin causes PyCharm projects not to load

### ISSUE THREAD

**Issue by ChuckWoodraska** [kiteco/plugins#73]
After installing the Kite Plugin for Pycharm I restart the IDE and none of my projects will load. After removing the plugin every works as normal.

On Ubuntu 16.04, Pycharm 2016.3.2. Also tried with Pycharm 2017.1 EAP.

Error message below:

INFO - roject.impl.ProjectManagerImpl - Fatal error initializing plugin com.kite.intellij 
com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin com.kite.intellij
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:249)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:509)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:120)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:104)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:91)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:285)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:246)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.c(ProjectManagerImpl.java:497)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager$6.run(CoreProgressManager.java:410)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:594)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.diagnostic.PluginException: com.intellij.openapi.util.BuildNumber.asStringWithAllDetails()Ljava/lang/String; [Plugin: com.kite.intellij]
	... 24 more

**Comment by ChuckWoodraska** [comment]
I assume this will be fixed when installing kite. I thought the plugin contained everything needed.

**Comment by adamsmith** [comment]
Hi Chuck, I think it should be but could you post the rest of the stack trace just in case so we can check it out?  It looks like it got cut off just as it was getting interesting (the `com.kite.intellij... 24 more`).

Thanks!

**Comment by ChuckWoodraska** [comment]
There was a little bit more that I missed. I don't know how to make PyCharm spit out more detailed logs than that for the IDE.

Caused by: java.lang.NoSuchMethodError: com.intellij.openapi.util.BuildNumber.asStringWithAllDetails()Ljava/lang/String;
	at KiteProjectComponent.initComponent(KiteProjectComponent.java:123)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:491)
	... 21 more

**Comment by adamsmith** [comment]
Thanks, this was actually an issue.  It's now fixed, though you can't get Kite through installing the plugin directly.  If you'd like a Kite invite email my first name at kite dot com  : )  Cheers!
